### ISSUE TITLE
Alegreya Sans SC do not show the small i

### ISSUE THREAD

**Issue by RGB-es** [huertatipografica/Alegreya-Sans#1]
![alegreyasanserror](https://cloud.githubusercontent.com/assets/7756783/17080235/cc01d0ba-5127-11e6-9c88-365ccb55e93e.png)
As you can see on the screenshot, Alegreya Sans SC do not show the small "i" nor it's accented variant (it has no problem with the capital I). I'm using the otf files (downloaded today) and can see the error on both, XeTeX and LibO Writer. I do not see the problem with the other weights of Alegreya Sans SC, just with the Italic.

**Comment by juandelperal** [comment]
Thanks! It was a software update related problem. Fixed
