### ISSUE TITLE
u-cy.sc is smaller and thinner than other small caps

### ISSUE THREAD

**Issue by combdn** [huertatipografica/Alegreya-Sans#12]
Hi.

It seems that you’ve fixed u-cy.sc shape recently (Y → У) but now it is thinner and smaller than other small caps :(
<img width="707" alt="screenshot 2018-01-04 12 59 26" src="https://user-images.githubusercontent.com/889260/34560722-a701e2fe-f14f-11e7-8aa2-6985a2b1db5b.png">

**Comment by juandelperal** [comment]
Thanks for reporting this issue. I will take a look and fix it
Best

**Comment by juandelperal** [comment]
HI! This is fixed now. https://github.com/huertatipografica/Alegreya-Sans/releases/tag/v2.007
