### ISSUE TITLE
Variable version?

### ISSUE THREAD

**Issue by cssobral2013** [huertatipografica/Alegreya-Sans#20]

**Comment by cssobral2013** [comment]
- [ ] 

- [ ] 

- [ ] 

- [ ]

**Comment by cssobral2013** [comment]
Sorry for closing this so soon - my touchpad is buggy.

**Comment by ghost** [comment]
[TypeNetwork/Alegreya-Sans](/TypeNetwork/Alegreya-Sans) has a variable version with weight axis.

**Comment by cssobral2013** [comment]
@shimmark - Thank You!
