### ISSUE TITLE
Release version numbers

### ISSUE THREAD

**Issue by rakuco** [huertatipografica/Alegreya-Sans#6]
I package alegreya-sans for FreeBSD, and was working on updating it to 2.001 there. It'd be great if the version numbers could follow a consistent versioning scheme: for example, instead of 2.001, make it 2.1, or always use X.Y.Z instead (2.0.1, 2.1.0 etc).

**Comment by rakuco** [comment]
(I think this also applies to Alegreya)

**Comment by juandelperal** [comment]
Hi Raphael 
Thanks for the suggestion but it is not possible:
![screen shot 2017-06-30 at 12 48 26](https://user-images.githubusercontent.com/2414972/27743482-8a82a740-5d92-11e7-9dc5-c315c73c1465.png)

Also we are following this convention:
https://groups.google.com/forum/#!msg/googlefonts-discuss/w6-i0Opikbc/Dj_tNw8epYUJ

**Comment by rakuco** [comment]
Thanks for the additional context. If I understood that discussion correctly, we're always dealing with MAJOR.MINOR here, where MINOR will be either 0 or 3-digit number that's always being incremented until you decide to bump MAJOR and go back to 0, right? In other words, there will never be a 2.1, but rather 2.002 and 2.100 (which would be the 101th 2.x release).
