### ISSUE TITLE
Scale has increased in SC family

### ISSUE THREAD

**Issue by m4rc1e** [huertatipografica/Alegreya-Sans#8]
In the latest commit, the scale of the letters has increased in the Black and ExtraBold styles.

![alegreya-sans-jump](https://user-images.githubusercontent.com/7525512/31071140-d52040b6-a75a-11e7-9bc3-f9c42edccef7.gif)

 I don't know if this was intentional?

Also, I think this is a Glyphs issue but the composite Glyphs now look like each component has a stroke applied to them.

![screen shot 2017-10-02 at 10 22 20](https://user-images.githubusercontent.com/7525512/31071354-a17b9200-a75b-11e7-80c8-3aad61228ec2.png)
*View full size*

**Comment by juandelperal** [comment]
Hi Marc, this is very strange. No, it is not intentional.
Now I am running with a new project but will check and fix this and the
ligatures problem after that.
Thanks!

2017-10-02 6:23 GMT-03:00 Marc Foley <notifications@github.com>:

**Comment by juandelperal** [comment]
Marc, I can't reproduce this errors.
Anyway I am about to add a new release including small cap fi and fl

**Comment by m4rc1e** [comment]
Was probably an issue with Glyphsapp. I genned it from a cutting edge release.
